services:
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
    volumes:
      - ./nginx/log:/var/log/nginx/
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl.crt:/etc/nginx/certs/ssl.crt
      - ./nginx/ssl.key:/etc/nginx/certs/ssl.key
    networks:
      - khuyenmai-vuanem

  frontend:
    container_name: khuyenmai-vuanem-frontend
    build: .
    restart: unless-stopped
    networks:
      - khuyenmai-vuanem

networks:
  khuyenmai-vuanem:
